FROM golang:1.10 as builder

RUN mkdir -p /go/src/yulong-hids
WORKDIR /go/src/yulong-hids
ADD . /go/src/yulong-hids
RUN go build -o ./web/web --ldflags='-w -s -linkmode external -extldflags "-static"' ./web/main.go

FROM alpine
MAINTAINER Jason Cooper "mrderek@protonmail.com"
COPY --from=builder /go/src/yulong-hids/web/web .
COPY --from=builder /go/src/yulong-hids/web/views .
COPY --from=builder /go/src/yulong-hids/web/static .
COPY --from=builder /go/src/yulong-hids/web/https_cert .
RUN mkdir /upload_files
RUN apk update
RUN apk upgrade
RUN apk add ca-certificates && update-ca-certificates
RUN apk add --update tzdata
ENV TZ=Asia/Shanghai
RUN rm -rf /var/cache/apk/*
RUN chmod +x web
ENTRYPOINT [ "./web" ]
